### ISSUE TITLE
Nana-MinGw (unrelated) 

### ISSUE THREAD

**Issue by qPCR4vir** [Pr0curo/rust_test_hw#1]
Hi,
sorry this is unrelated, but I din't found another way. Could you take look at: 
https://github.com/qPCR4vir/nana-docs/issues/1

Thank!

**Comment by Pr0curo** [comment]
i have partly updated the step by step guide, but it needs some more work.
the update will follow in the next days as requested.
also i'm happy to see someone read it.

**Comment by qPCR4vir** [comment]
Thank again!
.. well, your page have been read more than 22 times by more than 11 different users in the last month.
There are people compiling nana thank to you.

**Comment by Pr0curo** [comment]
done, see 
https://github.com/qPCR4vir/nana-docs/wiki/Install-and-use-nana-with-mingw---step-by-step#compiling-nana-step-by-stept---non-gui-version
